CREATE TABLE Cities(
CityID INT PRIMARY KEY,
Name VARCHAR(50))

CREATE TABLE Customers(
CustomerID INT PRIMARY KEY,
Name VARCHAR(50),
Birthday DATE,
CityID INT,
CONSTRAINT FK_Customer_City FOREIGN KEY(CityID) REFERENCES Cities(CityID))

CREATE TABLE Orders(
OrderID INT PRIMARY KEY,
CustomerID INT)

CREATE TABLE ItemTypes(
ItemTypeID INT PRIMARY KEY,
Name VARCHAR(50))

CREATE TABLE Items(
ItemID INT PRIMARY KEY,
Name VARCHAR(50),
ItemTypeID INT,
CONSTRAINT FK_Items_ItemType FOREIGN KEY(ItemTypeID) REFERENCES ItemTypes(ItemTypeID))

CREATE TABLE OrderItems(
OrderID INT,
ItemID INT,
PRIMARY KEY (OrderID, ItemID),
CONSTRAINT FK_OrderItems_Order FOREIGN KEY(OrderID) REFERENCES Orders(OrderID),
CONSTRAINT FK_OrderItems_Items FOREIGN KEY (ItemID) REFERENCES Items(ItemID))

ALTER TABLE Orders
ADD CONSTRAINT FK_Order_Customer FOREIGN KEY(CustomerID) REFERENCES Customers(CustomerID)